org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Force aapt2 to use the system-installed aarch64-compatible version
android.aapt2FromMavenOverride=/usr/bin/aapt2

# Prevent Gradle from downloading its own aapt2
android.disableResourceValidation=true
